# Generated by Django 5.0.6 on 2024-07-29 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='registration_number',
        ),
    ]
